#!/bin/bash
exec >sysstat-stop-stderrout.txt
exec 2>&1

echo "args: $@"
echo "hostname: `hostname`"

if [ -e sysstat-pids.txt ]; then
    while read pid; do
        kill -s SIGINT $pid
    done <sysstat-pids.txt
    find . -name "*stdout.txt" -o -name "*stderr.txt" -o -name "*.json" | while read line; do
	echo "Compressing: $line"
	xz -3 -T 0 $line
    done
else
    echo "Could not find sysstst-pids.txt"
    echo "PWD: `/bin/pwd`"
    echo "LS:"
    /bin/ls -l
    exit 1
fi
