#!/bin/bash
exec >sysstat-stop-stderrout.txt
exec 2>&1

echo "args: $@"
echo "hostname: `hostname`"

if [ -e sysstat-pids.txt ]; then
    while read pid; do
        kill -s SIGINT $pid
    done <sysstat-pids.txt
else
    echo "Could not find sysstst-pids.txt"
    exit 1
fi
